site: GPT2
url: unsupervisedpleasures.com
title: Unsupervised Pleasures
description: Experiments in machine learning with GPT-X and VQGAN-CLIP.
twitter:
  username: "@queermachines"
  card: summary
  creator: "@queermachines"
author:
  twitter: "@queermachines"
  name: "@queermachines"
  avatar:
  email: "queermachines@gmail.com"
  url: unsupervisedpleasures.com
permalink: pretty

baseurl: ""

highlighter: none

exclude:
  - .jekyll-cache

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]

sass:
  sass_dir:          _sass
  style:            :compressed

plugins:
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap

collections:
  pages:
    output: true
    permalink: /:name
  posts:
    output: true
    permalink: /texts/:slug

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
